[mypy]
python_version = 3.9
ignore_missing_imports = True
ignore_errors = True
namespace_packages = True
explicit_package_bases = True
mypy_path = packages/python/onnx9000-array/src,packages/python/onnx9000-backend-apple/src,packages/python/onnx9000-backend-cuda/src,packages/python/onnx9000-backend-native/src,packages/python/onnx9000-backend-rocm/src,packages/python/onnx9000-backend-webgpu/src,packages/python/onnx9000-c-compiler/src,packages/python/onnx9000-converters/src,packages/python/onnx9000-core/src,packages/python/onnx9000-diffusers/src,packages/python/onnx9000-jax/src,packages/python/onnx9000-json-extract/src,packages/python/onnx9000-onnx2gguf/src,packages/python/onnx9000-openvino/src,packages/python/onnx9000-optimizer/src,packages/python/onnx9000-optimum/src,packages/python/onnx9000-sphinx-demo/src,packages/python/onnx9000-tensorrt/src,packages/python/onnx9000-tflite-exporter/src,packages/python/onnx9000-toolkit/src,packages/python/onnx9000-tvm/src,packages/python/onnx9000-zoo/src,apps/cli/src
exclude = (?x)(
    ^tests/|
    ^apps/cli/tests/|
    ^packages/.*/tests/|
    ^pycdc/
  )

[mypy-tests.*]
ignore_errors = True
