[mypy]
python_version = 3.9
ignore_missing_imports = True
ignore_errors = True
namespace_packages = True
explicit_package_bases = True
exclude = (?x)(
    ^tests/|
    ^apps/cli/tests/|
    ^packages/.*/tests/|
    ^pycdc/
  )

[mypy-tests.*]
ignore_errors = True
