import { describe, it, expect, vi, beforeEach } from 'vitest';
import { LHSContainer } from '../../src/components/LHSContainer';
import { LHS_EXAMPLES } from '../../src/data/MockData';
import { globalEventBus } from '../../src/core/EventBus';

vi.mock('@onnx9000/converters', () => ({
  keras2onnx: vi.fn().mockResolvedValue(new Uint8Array(0)),
  convert: vi.fn().mockResolvedValue({
    nodes: [{ name: 'test_node', opType: 'Add', inputs: [], outputs: [] }],
    inputs: [],
    outputs: []
  })
}));

vi.mock('../../src/components/Dropdown', () => ({
  Dropdown: class {
    options: any;
    items: any[] = [];
    val: string | null = null;
    constructor(options: any) {
      this.options = options;
      this.val = options.initialValue || null;
    }
    mount() {}
    triggerChange(val: string) {
      this.val = val;
      if (this.options.onChange) this.options.onChange(val);
    }
    getValue() {
      return this.val;
    }
    updateItems(items: any[]) {
      this.items = items;
    }
    select(val: string) {
      this.val = val;
    }
  }
}));

vi.mock('../../src/components/FileTree', () => ({
  FileTree: class {
    options: any;
    constructor(options: any) {
      this.options = options;
    }
    mount() {}
    updateData = vi.fn();
    findNode = vi.fn().mockReturnValue(null);
    triggerSelect(path: string) {
      if (this.options.onSelect) this.options.onSelect(path);
    }
  }
}));

vi.mock('../../src/components/Editor', () => ({
  Editor: class {
    options: any;
    constructor(options: any) {
      this.options = options;
    }
    mount() {}
    openFile = vi.fn();
    triggerChange(val: string) {
      if (this.options.onChange) this.options.onChange(val);
    }
  }
}));

vi.mock('../../src/components/SplitPane', () => ({
  SplitPane: class {
    mount() {}
    getPanes() {
      return { pane1: document.createElement('div'), pane2: document.createElement('div') };
    }
  }
}));

describe('LHSContainer', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    localStorage.clear();
  });

  it('should render and mount components', () => {
    const container = new LHSContainer();
    const el = (container as any).element as HTMLElement;
    expect(el.className).toBe('demo-pane-lhs');
  });

  it('should update tree data when framework changes', () => {
    const container = new LHSContainer();
    container.mount(document.body);

    const fwDrop = (container as any).frameworkDropdown;
    const tree = (container as any).tree;
    const editor = (container as any).editor;

    fwDrop.triggerChange('tensorflow');

    expect(tree.updateData).toHaveBeenCalledWith(LHS_EXAMPLES['tensorflow'][0].root);
    expect(editor.openFile).toHaveBeenCalledWith(
      '/tf-mobilenet/export.py',
      '# /tf-mobilenet/export.py\n\n// Example generated by ONNX9000 Demo\n',
      'python'
    );
  });

  it('should update tree data when example changes', () => {
    const container = new LHSContainer();
    container.mount(document.body);

    const exDrop = (container as any).exampleDropdown;
    const tree = (container as any).tree;

    exDrop.triggerChange('keras-resnet');
    expect(tree.updateData).toHaveBeenCalledWith(LHS_EXAMPLES['keras'][1].root);
  });

  it('should open file in editor when tree item selected', () => {
    const container = new LHSContainer();
    container.mount(document.body);

    const tree = (container as any).tree;
    const editor = (container as any).editor;

    tree.triggerSelect('/tf-savedmodel/saved_model.pb');
    expect(editor.openFile).toHaveBeenCalledWith(
      '/tf-savedmodel/saved_model.pb',
      '# /tf-savedmodel/saved_model.pb\n\n// Example generated by ONNX9000 Demo\n',
      'python'
    );
  });

  it('should debounce editor change events', () => {
    vi.useFakeTimers();
    const consoleSpy = vi.spyOn(console, 'log').mockImplementation(() => {});

    const container = new LHSContainer();
    const editor = (container as any).editor;

    editor.triggerChange('new code');
    editor.triggerChange('new code 2');

    expect(consoleSpy).not.toHaveBeenCalled();
    vi.advanceTimersByTime(500);
    expect(consoleSpy).toHaveBeenCalledWith('Debounced editor change:', 10, 'bytes');

    vi.useRealTimers();
    consoleSpy.mockRestore();
  });

  it('should ignore missing framework on change', () => {
    const container = new LHSContainer();
    container.mount(document.body);
    const fwDrop = (container as any).frameworkDropdown;
    const exDrop = (container as any).exampleDropdown;

    fwDrop.triggerChange('fake-framework');

    expect(exDrop.items.length).toBe(0);
  });

  it('should run Keras conversion when run button is clicked and source is Keras', async () => {
    const container = new LHSContainer();
    container.mount(document.body);
    const btn = (container as any).runBtn;

    // The editor mock doesn't implement getValue
    (container as any).editor.getValue = vi.fn().mockReturnValue('{}');

    const emitSpy = vi.spyOn(globalEventBus, 'emit');
    btn.onclick();
    await new Promise((r) => setTimeout(r, 10)); // let promises resolve

    expect(emitSpy).toHaveBeenCalledWith('CONVERSION_COMPLETED', null);
    emitSpy.mockRestore();
  });

  it('should run generic conversion when run button is clicked and source is NOT Keras', async () => {
    const container = new LHSContainer();
    container.mount(document.body);
    const dropdown = (container as any).frameworkDropdown;
    dropdown.triggerChange('caffe');

    const btn = (container as any).runBtn;
    (container as any).editor.getValue = vi.fn().mockReturnValue('model content');

    const emitSpy = vi.spyOn(globalEventBus, 'emit');
    btn.onclick();
    await new Promise((r) => setTimeout(r, 10));

    expect(emitSpy).toHaveBeenCalledWith('ONNX_GRAPH_GENERATED', expect.anything());
    expect(emitSpy).toHaveBeenCalledWith('CONVERSION_COMPLETED', null);
    emitSpy.mockRestore();
  });

  it('should handle conversion errors gracefully', async () => {
    const container = new LHSContainer();
    container.mount(document.body);
    const btn = (container as any).runBtn;

    const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    // simulate a failure by throwing
    (container as any).editor.getValue = () => {
      throw new Error('Simulated error');
    };
    btn.onclick();
    await new Promise((r) => setTimeout(r, 10));
    expect(consoleSpy).toHaveBeenCalledWith(expect.stringContaining('Error: Simulated error'));
    consoleSpy.mockRestore();
  });
});

it('should ignore selection with missing content gracefully', () => {
  const container = new LHSContainer();
  container.mount(document.body);
  const tree = (container as any).tree;
  const editor = (container as any).editor;

  // Pass a dummy path that findNode returns empty
  tree.triggerSelect('/fake/path.py');
  expect(editor.openFile).toHaveBeenCalledWith(
    '/fake/path.py',
    '# /fake/path.py\n\n// Example generated by ONNX9000 Demo\n',
    'python'
  );
});

it('should ignore example change for missing framework or unmapped root', () => {
  const container = new LHSContainer();
  container.mount(document.body);
  const exDrop = (container as any).exampleDropdown;
  const tree = (container as any).tree;

  // Select example but fake fw
  (container as any).frameworkDropdown.val = 'fake-framework';
  exDrop.triggerChange('keras-resnet');

  expect(tree.updateData).not.toHaveBeenCalledWith(undefined);
});
