"""Mapping from ATen operators to onnx9000 IR operators."""

ATEN_OP_MAP = {
    "aten.add.Tensor": "Add",
    "aten.sub.Tensor": "Sub",
    "aten.mul.Tensor": "Mul",
    "aten.div.Tensor": "Div",
    "aten.mm.default": "MatMul",
    "aten.bmm.default": "MatMul",
    "aten.relu.default": "Relu",
    "aten.sum.default": "ReduceSum",
    "aten.mean.default": "ReduceMean",
    "aten.t.default": "Transpose",
    "aten.view.default": "Reshape",
    "aten.reshape.default": "Reshape",
    "aten.convolution.default": "Conv",
    "aten.max_pool2d_with_indices.default": "MaxPool",
    "aten.avg_pool2d.default": "AveragePool",
    "aten.batch_norm.default": "BatchNormalization",
    "aten.layer_norm.default": "LayerNormalization",
    "aten.softmax.int": "Softmax",
    "aten.log_softmax.int": "LogSoftmax",
    "aten.sigmoid.default": "Sigmoid",
    "aten.tanh.default": "Tanh",
    "aten.gelu.default": "Gelu",
    "aten.embedding.default": "Gather",
    "aten.stft.default": "STFT",
    "aten.istft.default": "ISTFT",
    "aten.fake_quantize_per_tensor_affine.default": "FakeQuantize",
}
