import { Region, Operation } from '../ir/core.js';

// 136-145. Standalone Web Generation
export class StandaloneJSExporter {
  emit(region: Region, modelWeightsUrl: string = './weights.bin'): { js: string; html: string } {
    const shaders: string[] = [];
    let executionQueue: string = '';

    // Dummy extraction of shaders and execution steps from region
    for (const block of region.blocks) {
      for (const op of block.operations) {
        if (op.opcode === 'web.hal.executable.create') {
          shaders.push(op.attributes.shader_code as string);
        } else if (op.opcode === 'web.hal.command_buffer.dispatch') {
          // 137, 141. Explicit, hardcoded dispatch queue (no loops)
          executionQueue += `    await dispatchKernel(device, pipelines[${shaders.length - 1}], 64, 64, 1);\n`;
        }
      }
    }

    // 138, 142, 144. Standalone strictly ES6 Module index.js
    const js = `// Auto-generated by onnx9000.iree
// Size: ~5KB
export class ModelRunner {
    constructor() {
        this.device = null;
        this.pipelines = [];
        this.memoryArena = null;
    }

    async init() {
        const adapter = await navigator.gpu?.requestAdapter();
        this.device = await adapter?.requestDevice();
        if (!this.device) throw new Error("WebGPU not supported");

        // 139. Embedded Shaders
        const shaders = ${JSON.stringify(shaders)};
        for (const code of shaders) {
            const module = this.device.createShaderModule({ code });
            this.pipelines.push(await this.device.createComputePipelineAsync({
                layout: 'auto',
                compute: { module, entryPoint: 'main' }
            }));
        }

        // 140. Static memory arena allocation
        this.memoryArena = this.device.createBuffer({
            size: 1024 * 1024,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC
        });

        // 143. Bundle weights via Fetch/CacheAPI
        const cache = await caches.open("model_weights");
        let res = await cache.match("${modelWeightsUrl}");
        if (!res) {
            res = await fetch("${modelWeightsUrl}");
            await cache.put("${modelWeightsUrl}", res.clone());
        }
        const weightsBuffer = await res.arrayBuffer();
        this.device.queue.writeBuffer(this.memoryArena, 0, weightsBuffer);
    }

    async run(inputBuffer) {
        this.device.queue.writeBuffer(this.memoryArena, 0, inputBuffer);
        
        // 137, 141. Explicit execution queue
${executionQueue}
    }
}

async function dispatchKernel(device, pipeline, x, y, z) {
    const encoder = device.createCommandEncoder();
    const pass = encoder.beginComputePass();
    pass.setPipeline(pipeline);
    pass.dispatchWorkgroups(x, y, z);
    pass.end();
    device.queue.submit([encoder.finish()]);
}
`;

    // 145. HTML Template with file input
    const html = `<!DOCTYPE html>
<html>
<head>
    <title>Standalone execution</title>
</head>
<body>
    <h1>Model Runner</h1>
    <input type="file" id="inputImage" />
    <script type="module">
        import { ModelRunner } from './index.js';
        const runner = new ModelRunner();
        await runner.init();
        
        document.getElementById('inputImage').addEventListener('change', async (e) => {
            const file = e.target.files[0];
            const buffer = await file.arrayBuffer();
            await runner.run(buffer);
            console.log("Inference complete");
        });
    </script>
</body>
</html>`;

    return { js, html };
  }
}
