import { describe, expect, it } from "vitest";
import * as arr from "../src/index";

describe("array", () => {
  it("should create EagerTensor", () => {
    const t = new arr.EagerTensor([1, 2, 3], "float32");
    expect(t.ndim).toBe(1);
    expect(t.numpy()).toEqual([1, 2, 3]);
    expect(t.data_val()).toEqual([1, 2, 3]);
    expect(t).toBeDefined();
    expect(t.cpu()).toBe(t);
    expect(t.gpu()).toBe(t);
    expect(t.quantize_dynamic()).toBe(t);
    t.dispose();
  });

  it("should create LazyTensor", () => {
    const t = new arr.LazyTensor("Add", []);
    expect(t).toBeDefined();
  });

  it("should toggle lazy evaluation", () => {
    arr.lazy_mode(true);
    expect(arr.IS_LAZY).toBe(true);
    arr.lazy_mode(false);
    expect(arr.IS_LAZY).toBe(false);
  });

  it("should run operations eagerly", () => {
    arr.lazy_mode(false);
    const t1 = new arr.EagerTensor([1, 2]);
    const t2 = new arr.EagerTensor([3, 4]);

    expect(arr.add(t1, t2)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.subtract(t1, t2)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.multiply(t1, t2)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.divide(t1, t2)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.power(t1, t2)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.mod(t1, t2)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.absolute(t1)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.negative(t1)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.sign(t1)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.exp(t1)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.log(t1)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.sqrt(t1)).toBeInstanceOf(arr.EagerTensor);
    expect(arr.square(t1)).toBeInstanceOf(arr.EagerTensor);

    // Check EagerTensor methods
    expect(t1.add(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.subtract(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.multiply(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.divide(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.power(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.mod(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.absolute()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.negative()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.sign()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.exp()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.log()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.sqrt()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.square(1)).toBeInstanceOf(arr.EagerTensor);

    expect(t1.sin()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.cos()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.tan()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.arcsin()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.arccos()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.arctan()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.sinh()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.cosh()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.tanh()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.arcsinh()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.arccosh()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.arctanh()).toBeInstanceOf(arr.EagerTensor);
    expect(t1.matmul(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.equal(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.less(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.greater(t2)).toBeInstanceOf(arr.EagerTensor);
    expect(t1.T).toBeInstanceOf(arr.EagerTensor);
  });

  it("should cover remaining ops in eager mode", () => {
    arr.lazy_mode(false);
    const t = new arr.EagerTensor([1]);
    expect(arr.less_equal(t)).toBeDefined();
    expect(arr.greater_equal(t)).toBeDefined();
    expect(arr.logical_and(t)).toBeDefined();
    expect(arr.logical_or(t)).toBeDefined();
    expect(arr.logical_not(t)).toBeDefined();
    expect(arr.logical_xor(t)).toBeDefined();
    expect(arr.isnan(t)).toBeDefined();
    expect(arr.isinf(t)).toBeDefined();
    expect(arr.where(t)).toBeDefined();
    expect(arr.sum(t)).toBeDefined();
    expect(arr.prod(t)).toBeDefined();
    expect(arr.mean(t)).toBeDefined();
    expect(arr.min(t)).toBeDefined();
    expect(arr.max(t)).toBeDefined();
    expect(arr.argmin(t)).toBeDefined();
    expect(arr.argmax(t)).toBeDefined();
    expect(arr.reshape(t)).toBeDefined();
    expect(arr.squeeze(t)).toBeDefined();
    expect(arr.expand_dims(t)).toBeDefined();
    expect(arr.concatenate(t)).toBeDefined();
    expect(arr.split(t)).toBeDefined();
    expect(arr.tile(t)).toBeDefined();
    expect(arr.pad(t)).toBeDefined();
    expect(arr.take(t)).toBeDefined();
    expect(arr.gather(t)).toBeDefined();
    expect(arr.sort(t)).toBeDefined();
    expect(arr.argsort(t)).toBeDefined();
    expect(arr.nonzero(t)).toBeDefined();
    expect(arr.zeros()).toBeDefined();
    expect(arr.ones()).toBeDefined();
    expect(arr.empty()).toBeDefined();
    expect(arr.full()).toBeDefined();
    expect(arr.eye()).toBeDefined();
    expect(arr.identity()).toBeDefined();
    expect(arr.arange()).toBeDefined();
    expect(arr.linspace()).toBeDefined();
    expect(arr.log10()).toBeDefined();
    expect(arr.log2()).toBeDefined();
    expect(arr.cbrt()).toBeDefined();
    expect(arr.reciprocal()).toBeDefined();
    expect(arr.deg2rad()).toBeDefined();
    expect(arr.rad2deg()).toBeDefined();
    expect(arr.dot()).toBeDefined();
    expect(arr.vdot()).toBeDefined();
    expect(arr.inner()).toBeDefined();
    expect(arr.outer()).toBeDefined();
    expect(arr.tensordot()).toBeDefined();
    expect(arr.einsum()).toBeDefined();
    expect(arr.swapaxes()).toBeDefined();
    expect(arr.trace()).toBeDefined();
    expect(arr.ptp()).toBeDefined();
    expect(arr.all()).toBeDefined();
    expect(arr.any()).toBeDefined();
    expect(arr.cumsum()).toBeDefined();
    expect(arr.cumprod()).toBeDefined();
    expect(arr.ravel()).toBeDefined();
    expect(arr.broadcast_to()).toBeDefined();
    expect(arr.stack()).toBeDefined();
    expect(arr.vstack()).toBeDefined();
    expect(arr.hstack()).toBeDefined();
    expect(arr.dstack()).toBeDefined();
    expect(arr.array_split()).toBeDefined();
    expect(arr.repeat()).toBeDefined();
    expect(arr.not_equal()).toBeDefined();
    expect(arr.allclose()).toBeDefined();
    expect(arr.isclose()).toBeDefined();
    expect(arr.extract()).toBeDefined();
    expect(arr.take_along_axis()).toBeDefined();
    expect(arr.put()).toBeDefined();
    expect(arr.put_along_axis()).toBeDefined();
    expect(arr.nan_to_num()).toBeDefined();
    expect(arr.clip()).toBeDefined();
    expect(arr.around()).toBeDefined();
    expect(arr.fix()).toBeDefined();
    expect(arr.i0()).toBeDefined();
    expect(arr.sinc()).toBeDefined();
    expect(arr.save()).toBeDefined();
    expect(arr.load()).toBeDefined();
    expect(arr.vectorize()).toBeDefined();
    expect(arr.meshgrid()).toBeDefined();
    expect(arr.mgrid()).toBeDefined();
    expect(arr.einsum_path()).toBeDefined();
    expect(arr.polyfit()).toBeDefined();
    expect(arr.histogram()).toBeDefined();
    expect(arr.digitize()).toBeDefined();
    expect(arr.export_model()).toBeDefined();
    expect(arr.compile()).toBeDefined();
    expect(arr.set_device()).toBeDefined();
    expect(arr.set_log_level()).toBeDefined();
    expect(arr.set_opset()).toBeDefined();
    expect(arr.set_num_threads()).toBeDefined();

    expect(arr.nn.relu(t)).toBeDefined();
    expect(arr.nn.sigmoid(t)).toBeDefined();
    expect(arr.nn.softmax(t)).toBeDefined();
    expect(arr.nn.log_softmax(t)).toBeDefined();
    expect(arr.nn.gelu(t)).toBeDefined();
    expect(arr.nn.conv2d(t)).toBeDefined();
    expect(arr.nn.max_pool2d(t)).toBeDefined();
    expect(arr.nn.avg_pool2d(t)).toBeDefined();
    expect(arr.nn.batch_norm(t)).toBeDefined();
    expect(arr.nn.layer_norm(t)).toBeDefined();
    expect(arr.nn.dropout(t)).toBeDefined();
    expect(arr.nn.linear(t)).toBeDefined();
    expect(arr.nn.cross_entropy_loss(t)).toBeDefined();

    expect(arr.linalg.norm(t)).toBeDefined();
    expect(arr.linalg.det(t)).toBeDefined();
    expect(arr.linalg.inv(t)).toBeDefined();
    expect(arr.linalg.solve(t)).toBeDefined();
    expect(arr.linalg.svd(t)).toBeDefined();

    expect(arr.char.add(t)).toBeDefined();
    expect(arr.char.equal(t)).toBeDefined();
    expect(arr.char.replace(t)).toBeDefined();

    expect(arr.random.rand(1)).toBeDefined();
    expect(arr.random.randn(1)).toBeDefined();
    expect(arr.random.randint(1)).toBeDefined();
    expect(arr.random.uniform(1)).toBeDefined();
    expect(arr.random.normal(1)).toBeDefined();
    expect(arr.random.seed(1)).toBeUndefined();
  });

  it("should run operations lazily", () => {
    arr.lazy_mode(true);
    const t = new arr.LazyTensor("Add", []);
    expect(arr.add(t, t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.subtract(t, t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.multiply(t, t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.divide(t, t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.power(t, t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.mod(t, t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.absolute(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.negative(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.sign(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.exp(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.log(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.sqrt(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.square(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.sin(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.cos(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.tan(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.arcsin(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.arccos(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.arctan(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.sinh(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.cosh(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.tanh(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.arcsinh(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.arccosh(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.arctanh(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.matmul(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.equal(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.less(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.greater(t)).toBeInstanceOf(arr.LazyTensor);

    expect(arr.less_equal(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.greater_equal(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.logical_and(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.logical_or(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.logical_not(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.logical_xor(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.isnan(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.isinf(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.where(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.sum(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.prod(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.mean(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.min(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.max(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.argmin(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.argmax(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.reshape(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.squeeze(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.expand_dims(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.concatenate(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.split(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.tile(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.pad(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.transpose(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.take(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.gather(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.sort(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.argsort(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nonzero(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.zeros()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.ones()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.empty()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.full()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.eye()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.identity()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.arange()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.linspace()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.log10()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.log2()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.cbrt()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.reciprocal()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.deg2rad()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.rad2deg()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.dot()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.vdot()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.inner()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.outer()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.tensordot()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.einsum()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.swapaxes()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.trace()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.ptp()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.all()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.any()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.cumsum()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.cumprod()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.ravel()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.broadcast_to()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.stack()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.vstack()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.hstack()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.dstack()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.array_split()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.repeat()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.not_equal()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.allclose()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.isclose()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.extract()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.take_along_axis()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.put()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.put_along_axis()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nan_to_num()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.clip()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.around()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.fix()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.i0()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.sinc()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.save()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.load()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.vectorize()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.meshgrid()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.mgrid()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.einsum_path()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.polyfit()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.histogram()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.digitize()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.export_model()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.compile()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.set_device()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.set_log_level()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.set_opset()).toBeInstanceOf(arr.LazyTensor);
    expect(arr.set_num_threads()).toBeInstanceOf(arr.LazyTensor);

    expect(arr.nn.relu(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.sigmoid(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.softmax(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.log_softmax(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.gelu(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.conv2d(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.max_pool2d(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.avg_pool2d(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.batch_norm(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.layer_norm(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.dropout(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.linear(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.nn.cross_entropy_loss(t)).toBeInstanceOf(arr.LazyTensor);

    expect(arr.linalg.norm(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.linalg.det(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.linalg.inv(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.linalg.solve(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.linalg.svd(t)).toBeInstanceOf(arr.LazyTensor);

    expect(arr.char.add(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.char.equal(t)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.char.replace(t)).toBeInstanceOf(arr.LazyTensor);

    expect(arr.random.rand(1)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.random.randn(1)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.random.randint(1)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.random.uniform(1)).toBeInstanceOf(arr.LazyTensor);
    expect(arr.random.normal(1)).toBeInstanceOf(arr.LazyTensor);
  });

  it("should construct Errors", () => {
    expect(new arr.BroadcastError("test").message).toBe("test");
    expect(new arr.TypeMismatchError("test").message).toBe("test");
  });
});
