/* eslint-disable */
import { Program } from './ast.js';
import { UnsupportedOpError } from './errors.js';

export function lintMILProgram(program: Program): void {
  // 295. Add strict linter enforcing that no proprietary/undocumented Apple MIL opcodes are generated
  const documentedAppleOps = new Set([
    'add',
    'sub',
    'mul',
    'real_div',
    'pow',
    'abs',
    'ceil',
    'floor',
    'round',
    'exp',
    'log',
    'sqrt',
    'sin',
    'cos',
    'tan',
    'asin',
    'acos',
    'atan',
    'sign',
    'mod',
    'maximum',
    'minimum',
    'erf',
    'isnan',
    'relu',
    'leaky_relu',
    'sigmoid',
    'tanh',
    'softmax',
    'log_softmax',
    'elu',
    'hard_sigmoid',
    'softplus',
    'softsign',
    'prelu',
    'gelu',
    'clip',
    'reduce_mean',
    'reduce_sum',
    'reduce_max',
    'reduce_min',
    'reduce_prod',
    'reduce_log_sum_exp',
    'argmax',
    'argmin',
    'nms',
    'topk',
    'non_zero',
    'equal',
    'greater',
    'greater_equal',
    'less',
    'less_equal',
    'logical_not',
    'logical_and',
    'logical_or',
    'logical_xor',
    'select',
    'cond',
    'while_loop',
    'lstm',
    'gru',
    'rnn',
    'reshape',
    'transpose',
    'concat',
    'slice_by_index',
    'slice_by_size',
    'split',
    'squeeze',
    'expand_dims',
    'gather',
    'gather_along_axis',
    'gather_nd',
    'scatter',
    'scatter_along_axis',
    'scatter_nd',
    'tile',
    'pad',
    'broadcast_to',
    'shape',
    'size',
    'cast',
    'conv',
    'conv_transpose',
    'max_pool',
    'avg_pool',
    'global_max_pool',
    'global_avg_pool',
    'batch_norm',
    'instance_norm',
    'layer_norm',
    'identity',
    'matmul',
    'linear',
    'resize_bilinear',
    'resize_nearest_neighbor',
    'const',
    'isinf',
    'local_response_norm',
    'max_unpool',
    'pixel_shuffle',
    'space_to_depth',
    'constexpr_affine_dequantize',
    'constexpr_lut_dequantize',
    'constexpr_sparse_dequantize',
    'read_state',
    'write_state',
    'scaled_dot_product_attention',
    'hard_swish',
  ]);

  for (const fnName in program.functions) {
    const fn = program.functions[fnName]!;
    for (const blockName in fn.blocks) {
      const block = fn.blocks[blockName]!;
      for (const op of block.operations) {
        if (!documentedAppleOps.has(op.opType)) {
          throw new UnsupportedOpError(
            op.opType,
            'Proprietary or undocumented Apple MIL opcode generated',
          );
        }
      }
    }
  }
}
