export class BufferMapper {}
export class WasmIndirectCaller {}
export class WebGPUSubgroups {}
export class WGSLRingBuffer {}
export class AsyncPipelineCompiler {}
export class CustomMemoryAllocator {}
export class JSPauseMinimizer {}
export class FP16WebGPUExtension {}
export class WeightsPrefetcher {}
export class MoEShaderGenerator {}
